name: Deploy Chief of Staff to Azure Container Apps

on:
  push:
    branches: [main]
    paths: ['chief-of-staff/**']
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: aistaffsuite.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./chief-of-staff
        platforms: linux/amd64
        push: true
        tags: aistaffsuite.azurecr.io/ai-staff-chief-of-staff:${{ github.sha }},aistaffsuite.azurecr.io/ai-staff-chief-of-staff:latest
        
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        
    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: aistaffsuite
        containerAppName: ai-staff-chief-of-staff
        resourceGroup: ai-staff-suite-rg
        imageToDeploy: aistaffsuite.azurecr.io/ai-staff-chief-of-staff:${{ github.sha }}
        environmentVariables: |
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL=gpt-4o-mini
          OPENAI_TEMPERATURE=0.7
          AGENT_NAME="Chief of Staff"

